#install R packages
RUN wget http://ac-client.oss-cn-beijing.aliyuncs.com/youcan/qvalue_2.6.0.tar.gz &&\
	R CMD INSTALL qvalue_2.6.0.tar.gz && rm -rf qvalue_2.6.0.tar.gz &&\
		rm -rf /var/cache/apk/* && rm -rf /root/cache/* && rm -rf /tmp/*
#install imagemagick
RUN apk add imagemagick
